[package]
name = "luma-installer"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "luma-install-helper"
path = "src/main.rs"

[dependencies]
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_Registry", "Win32_System_Environment"] }
